export const environment = {
  production: true,
  apiUrl: 'https://trungdc.synology.me:5152/auction',
  api_url_list_price_step: this.apiUrl + '/api/v1/pricestep',
  api_url_list_category: this.apiUrl + '/api/v1/category',
  api_url_list_user: this.apiUrl + '/api/v1/users',
  api_url_list_img_url: this.apiUrl + '/api/v1/users/{id}',
  API_URL_AUCTION: this.apiUrl + '/auction/api',
  api_url_order_status: this.apiUrl + '/api/v1/payments',
  categoryUrl: this.apiUrl + '/api/v1/products/category',
  priceStepUrl: this.apiUrl + '/api/v1/products/priceStep',
  transactionUrl: this.apiUrl + '/auction/api/transaction',
  productSearchUrl: this.apiUrl + '/api/v1/products/search',
  userUrl: this.apiUrl + '/api/user/v1/',
  uri_api_create_user_v1_user: this.apiUrl + '/api/v1/users/create',
  uri_api_update_user_v1_user: this.apiUrl + '/api/v1/users/update',
  uri_api_find_by_id_user_v1_user: this.apiUrl + '/api/v1/users/find/',
  firebaseConfig: {
    apiKey: 'AIzaSyDRWAv_6CkY0N5ocqceEDbh5gc2UankMXo',
    authDomain: 'truonglh-68106.firebaseapp.com',
    projectId: 'truonglh-68106',
    storageBucket: 'truonglh-68106.appspot.com',
    messagingSenderId: '680493532790',
    appId: '1:680493532790:web:4d7b3923a9e9d4f00ac157',
    measurementId: 'G-YRDCYMF4H9',
  },
  LOGIN_API: this.apiUrl + '/api/auth/login',
  GOOGLE_LOGIN_API: this.apiUrl + '/api/auth/google',
  DIA_GIOI_VIETNAM_API: 'https://raw.githubusercontent.com/kenzouno1/DiaGioiHanhChinhVN/master/data.json',
};
