const apiUrl = 'https://trungdc.synology.me:5152/auction';
export const environment = {
  production: false,
  firebaseConfig: {
    apiKey: 'AIzaSyDV8RZyn7riFw087ES5nA05z4ON5axBO28',
    authDomain: 'test-42050.firebaseapp.com',
    databaseURL: 'https://test-42050-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'test-42050',
    storageBucket: 'test-42050.appspot.com',
    messagingSenderId: '902879698828',
    appId: '1:902879698828:web:2d7346b0c1c599d08540a9',
    measurementId: 'G-XEHPX24EFX'
  },
  categoryUrl: apiUrl + '/api/v1/products/category',
  priceStepUrl: apiUrl + '/api/v1/products/priceStep',
  transactionUrl: apiUrl + '/api/v1/auction/transaction',
  productSearchUrl: apiUrl + '/api/v1/products/search',
  userUrl: apiUrl + '/api/v1/users',
  urlAddAccountUser: apiUrl + '/api/user/v1/add',
  api_url_products: apiUrl + '/api/v1/products',
  api_url_list_price_step: apiUrl + '/api/v1/pricestep',
  api_url_list_category: apiUrl + '/api/v1/category',
  api_url_list_user: apiUrl + '/api/v1/users',
  api_url_list_img_url: apiUrl + '/api/v1/users/{id}',
  API_URL_AUCTION: apiUrl + '/api/v1/auction',
  api_url_order_status: apiUrl + '/api/v1/payments',
  API_TOP_USER: apiUrl + '/api/user/v1/top',
  api_url_list_price_range: apiUrl + '/api/v1/product-properties/price-range',
  api_url_list_auction_status: apiUrl + '/api/v1/product-properties/auction-status',
  api_url_search_by_list_id: apiUrl + '/api/v1/products/find-by-list-id',
  api_url_remove_products: apiUrl + '/api/v1/products/remove',
  api_url_find_by_id: apiUrl + '/api/v1/products/find-by-id/',
  api_url_review_product: apiUrl + '/api/v1/products/review/',
  api_url_write_reason: apiUrl + '/api/v1/products/reason',
  api_url_get_reason: apiUrl + '/api/v1/products/reason/',
  api_url_do_not_review_product: apiUrl + '/api/v1/products/do-not-review/',
  api_url_get_imgs: apiUrl + '/api/v1/products/imgs/',
  api_url_list_user_list_id: apiUrl + '/api/v1/users/find-by-list-id',
  transactionDeleteUrl: apiUrl + '/api/v1/auction/delete',
  transactionFindByListIdUrl: apiUrl + '/api/v1/auction/find-by-list-id',
  api_url_userType: apiUrl + '/api/v1/users/usersType',
  productUrl: apiUrl + '/api/v1/products',
  imageUrl: apiUrl + '/api/v1/products/img',
  API_URL_GUIDE: apiUrl + '/api/v1/guide',
  SIGN_IN_API: apiUrl + '/api/v1/auth/signin',
  GOOGLE_SIGN_IN_API: apiUrl + '/api/v1/auth/google',
  uri_api_create_user_v1_user: apiUrl + '/api/v1/users/create',
  api_url_create_img_url: apiUrl + '/api/v1/products/img/create',
  uri_api_update_user_v1_user: apiUrl + '/api/v1/users/update',
  uri_api_find_by_id_user_v1_user: apiUrl + '/api/v1/users/getUserById',
  uri_api_find_all_user_v1: apiUrl + '/api/v1/users/findAll',
  api_url_product_history_list: apiUrl + '/api/v1/products/list/',
  api_url_product_auction_canceled: apiUrl + '/api/v1/products/canceled/',
  api_url_product_auction_history: apiUrl + '/api/v1/auction/list/',
  NQV_LOCK_ACCOUNT:apiUrl + '/api/v1/users/lockUser',
  NQV_GET_ACCOUNT_BY_ID_API: apiUrl + '/api/v1/accounts/getAccountById',
  LOGIN_API: apiUrl + '/api/auth/login',
  GOOGLE_LOGIN_API: apiUrl + '/api/auth/google',
  DIA_GIOI_VIETNAM_API: 'https://raw.githubusercontent.com/kenzouno1/DiaGioiHanhChinhVN/master/data.json',
  api_url_shipping: apiUrl + '/api/v1/payments/update',
  api_url_order_status_1: apiUrl + 'api/v1/payments/find-by-list-id',
};
