export const environment = {
  production: true,
  apiUrl: 'https://trungdc.synology.me:5152/auction',
  firebaseConfig: {
    apiKey: 'AIzaSyDV8RZyn7riFw087ES5nA05z4ON5axBO28',
    authDomain: 'test-42050.firebaseapp.com',
    databaseURL: 'https://test-42050-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'test-42050',
    storageBucket: 'test-42050.appspot.com',
    messagingSenderId: '902879698828',
    appId: '1:902879698828:web:2d7346b0c1c599d08540a9',
    measurementId: 'G-XEHPX24EFX'
  },
  categoryUrl: this.apiUrl + '/api/v1/products/category',
  priceStepUrl: this.apiUrl + '/api/v1/products/priceStep',
  transactionUrl: this.apiUrl + '/auction/api/transaction',
  productSearchUrl: this.apiUrl + '/api/v1/products/search',
  userUrl: this.apiUrl + '/api/v1/users',
  urlAddAccountUser: this.apiUrl + '/api/user/v1/add',
  api_url_products: this.apiUrl + '/api/v1/products',
  api_url_list_price_step: this.apiUrl + '/api/v1/pricestep',
  api_url_list_category: this.apiUrl + '/api/v1/category',
  api_url_list_user: this.apiUrl + '/api/v1/users',
  api_url_list_img_url: this.apiUrl + '/api/v1/users/{id}',
  API_URL_AUCTION: this.apiUrl + '/api/v1/auction',
  api_url_order_status: this.apiUrl + '/api/v1/payments',
  API_TOP_USER: this.apiUrl + '/api/user/v1/top',
  api_url_list_price_range: this.apiUrl + '/api/v1/product-properties/price-range',
  api_url_list_auction_status: this.apiUrl + '/api/v1/product-properties/auction-status',
  api_url_search_by_list_id: this.apiUrl + '/api/v1/products/find-by-list-id',
  api_url_remove_products: this.apiUrl + '/api/v1/products/remove',
  api_url_find_by_id: this.apiUrl + '/api/v1/products/find-by-id/',
  api_url_review_product: this.apiUrl + '/api/v1/products/review/',
  api_url_write_reason: this.apiUrl + '/api/v1/products/reason',
  api_url_get_reason: this.apiUrl + '/api/v1/products/reason/',
  api_url_do_not_review_product: this.apiUrl + '/api/v1/products/do-not-review/',
  transactionDeleteUrl: this.apiUrl + '/api/v1/auction/delete',
  transactionFindByListIdUrl: this.apiUrl + '/api/v1/auction/find-by-list-id',
  api_url_userType: this.apiUrl + '/api/v1/users/usersType',
  productUrl: this.apiUrl + '/api/v1/products',
  imageUrl: this.apiUrl + '/api/v1/products/img',
  API_URL_GUIDE: this.apiUrl + '/api/v1/guide',
  SIGN_IN_API: this.apiUrl + '/api/v1/auth/signin',
  GOOGLE_SIGN_IN_API: this.apiUrl + '/api/v1/auth/google',
  uri_api_create_user_v1_user: this.apiUrl + '/api/v1/users/create',
  api_url_create_img_url: this.apiUrl + '/api/v1/products/img/create',
  uri_api_update_user_v1_user: this.apiUrl + '/api/v1/users/update',
  uri_api_find_by_id_user_v1_user: this.apiUrl + '/api/v1/users/find/',
  LOGIN_API: this.apiUrl + '/api/auth/login',
  GOOGLE_LOGIN_API: this.apiUrl + '/api/auth/google',
  DIA_GIOI_VIETNAM_API: 'https://raw.githubusercontent.com/kenzouno1/DiaGioiHanhChinhVN/master/data.json'
};
